name:           Example4
version:        0.0.1

description: 
    version 0.0.1 - a example minimal project
dependencies:
  - base == 4.*
  - hgeometry
  - hgeometry-combinatorial

ghc-options: -Wall

executables:
  Run_Example:
    main: TheMain.hs
    source-dirs: app


